/**
 * Roman Urdu tutor text — word meaning, memory tricks (not instruction translations)
 */
const EXPLANATION_UR_BY_ID = {
  rs01: "Fake words jaise florptine, branthole ajeeb lagte hain — real words tum ne reading mein dekhe honge: ephemeral, resilient.",
  rs02: "Ameliorate, dichotomy, paradigm academic hain — torplish, wexnify fake lagte hain kyunki unka koi clear matlab nahi.",
  rs03: "Cogent, tenuous, laconic, pernicious real hain — plintar, frobbish dictionary words nahi.",
  rs04: "Benevolent, surreptitious, ostensible real register hain — crindol, malkive nonsense hain.",
  rs05: "Mitigate, prolific, arduous, esoteric asli words hain — blorvex, snazzle matlab ke baghair hain.",
  rs06: "Gregarious, insidious, magnanimous, recalcitrant C2 level hain — thwompish, crelvine fake.",
  rs07: "Anomaly, capricious, inherent, juxtapose real hain — frindlep, morvex invented.",
  rs08: "Alacrity, fastidious, idiosyncrasy, superfluous real hain — wexmond, clorvish fake.",
  rs09: "Circumspect, diminutive, precarious, voracious real hain — plorvane, snazzwort fake.",
  rs10: "Obfuscate, salient, taciturn, veracity real hain — trindlep, morplish fake.",
  rs11: "Parsimonious, effervescent, intransigent, perfunctory academic hain — clemtor, brindlox fake.",
  rs12: "Hypothesis, empirical, corroborate, synthesis science words hain — grindlep, snorvex fake.",
  fb01: "'Scrutinized' matlab gehri nazar se check — peer review findings ko carefully dekhta hai.",
  fb02: "'Incorporate' matlab shamil karna — green space ko development plan mein add karna.",
  fb03: "'Alleviate' matlab kam karna ya halka karna — treaty tensions ease karti hai. 'Exacerbate' ulta barhata hai.",
  fb04: "'Cogent' matlab strong convincing — aisi argument ke critics bhi agree karein.",
  fb05: "'Skeptical' matlab doubtful — scientists abhi fully sure nahi compound ke long effects se.",
  fb06: "'Chronicle' matlab record/document — museum history ko primary sources se likhta hai.",
  fb07: "'Accelerated' matlab tezi se barhna — renewable energy adoption fast grow hui.",
  fb08: "'Replete' matlab bharpur filled — lecture anecdotes se full thi.",
  fb09: "'Underestimate' matlab kam andaza — automation ka economic impact ignore nahi ho sakta.",
  fb10: "'Metamorphosis' matlab complete change — identity transform hoti hai.",
  fb11: "'Mandate' matlab require/order — laws batati hain companies data kaise collect karein.",
  fb12: "'Resume' matlab talks dobara shuru — incident ke baad negotiations restart.",
  wp01: "Photo describe karte waqt who, what, where bolo — farmers market lively scene hai.",
  wp02: "Library scene: students + laptops + books — present continuous use karo actions ke liye.",
  wp03: "Family, dog, park, autumn — 2-3 clear sentences kaafi hain DET ke liye.",
  wp04: "Chef + open kitchen — action aur setting dono mention karo.",
  wp05: "Cyclists + bike lane + safety — simple present/continuous mix chalega.",
  wp06: "Rain + umbrellas + bus stop — weather aur activity dono describe karo.",
  iw01: "Remote work: opinion + 2 reasons + conclusion — flexible time acha, collaboration mushkil ho sakti hai.",
  iw02: "Community service optional better — mandatory insincere lag sakta hai busy students ke liye.",
  iw03: "Social media: risks aur benefits dono — digital literacy solution hai, total ban nahi.",
  iw04: "Public transport investment — environment, jobs access, long-term benefit explain karo.",
  iw05: "Plastic ban: oceans, wildlife, reusable bags — environment vs convenience balance.",
  ws01: "Personal story: challenge, action, lesson — past tense story, present tense lesson learned.",
  cs01: "Solar panels 'become' cheaper — general truth present. Governments 'offer' incentives.",
  cs02: "She 'reviews' data har morning — singular subject. Team 'identifies' patterns.",
  cs03: "Experiment 'demonstrates' — singular. Results 'support' studies.",
  cs04: "Noise 'disturbs' residents — plural subject. Ordinances 'will' limit hours — future rule.",
  cs05: "Founders 'ignore' feedback — plural. They 'survive' longer — plural verb.",
  cs06: "Water 'boils' at 100°C — scientific fact singular. This 'is' a property.",
  cp01: "Ethical guidelines sentence fit karti hai AI healthcare topic ke baad — cooking/basketball off-topic.",
  cp02: "Flexible schedules wala sentence online education flow continue karta hai.",
  cp03: "Microplastics food chain sentence oceans pollution topic continue karti hai.",
  cp04: "Protecting forests conclusion hai biodiversity passage ka.",
  cp05: "Renewable electricity without fossil fuels sentence wind/solar paragraph complete karti hai.",
  ha01: "Trees reduce heat + air quality — yahi sentence 'why plant trees' ka jawab hai.",
  ha02: "Software bug extra week testing — launch delay ka reason yahi hai.",
  ha03: "Photosynthesis definition wali line — process plants light convert karte hain.",
  ha04: "40 gallons one session — camel water question ka direct answer.",
  ha05: "Rising server costs staff cut — startup ne staff is liye kam ki.",
  ii01: "Poora passage sleep importance — 'adequate sleep vital' main idea hai.",
  ii02: "Recycling = sorting + awareness — participation campaigns matter.",
  ii03: "Remote work = tools + management norms — communication key hai.",
  ii04: "EV adoption ke multiple factors — batteries, credits, emissions concern.",
  ii05: "Vaccination individuals + communities dono benefit — herd immunity point.",
  tp01: "Volcanoes formation + communities — title poora passage cover kare.",
  tp02: "Mindfulness benefits studies + schools/workplaces — evidence-based title.",
  tp03: "Digital privacy concerns + laws — regulation theme title mein ho."
};
