/**
 * DET Practice — Word Bank (120 words, 8 categories × 15)
 */

const WORD_BANK = [
  // ── Academic & Formal (15) ──
  {
    word: 'ephemeral',
    phonetic: 'ee-FEM-er-al',
    pos: 'adj',
    meaningEN: 'Lasting for a very short time.',
    meaningUR: 'Jo thori der ke liye hota ho, jaldi khatam ho jaye.',
    synonyms: ['transient', 'fleeting'],
    example: 'Social media trends are often ephemeral, fading within weeks.',
    memoryTip: 'EPI = upon + HEMERA (Greek day) → lasting one day.',
    category: 'Academic & Formal'
  },
  {
    word: 'dichotomy',
    phonetic: 'dy-KOT-uh-mee',
    pos: 'noun',
    meaningEN: 'A division into two sharply opposed parts.',
    meaningUR: 'Do alag alag cheezon ka clear farq ya division.',
    synonyms: ['division', 'split'],
    example: 'The essay explores the dichotomy between theory and practice.',
    memoryTip: 'DI = two + TOMY (cutting) → cut in two.',
    category: 'Academic & Formal'
  },
  {
    word: 'paradigm',
    phonetic: 'PAIR-uh-dyme',
    pos: 'noun',
    meaningEN: 'A typical example or model of how something is done.',
    meaningUR: 'Koi standard model ya soch ka tareeqa jis par sab follow karte hain.',
    synonyms: ['model', 'framework'],
    example: 'Einstein shifted the paradigm of modern physics.',
    memoryTip: 'Think "pair of dime" — a standard pattern everyone uses.',
    category: 'Academic & Formal'
  },
  {
    word: 'pragmatic',
    phonetic: 'prag-MAT-ik',
    pos: 'adj',
    meaningEN: 'Dealing with problems in a practical, realistic way.',
    meaningUR: 'Practical soch wala, jo kaam ki baat kare na sirf theory.',
    synonyms: ['practical', 'feasible'],
    example: 'A pragmatic approach focuses on what actually works.',
    memoryTip: 'PRAGMA (Greek) = deed/action → action over theory.',
    category: 'Academic & Formal'
  },
  {
    word: 'corroborate',
    phonetic: 'kuh-ROB-uh-rayt',
    pos: 'verb',
    meaningEN: 'To confirm or support something with evidence.',
    meaningUR: 'Kisi baat ko proof ya evidence se confirm karna.',
    synonyms: ['substantiate', 'confirm'],
    example: 'Witness testimony helped corroborate the researcher\'s findings.',
    memoryTip: 'CO + ROBOR (strength) → strengthen a claim with proof.',
    category: 'Academic & Formal'
  },
  {
    word: 'nuanced',
    phonetic: 'NOO-ahnst',
    pos: 'adj',
    meaningEN: 'Characterized by subtle differences in meaning or tone.',
    meaningUR: 'Jisme choti choti baatein aur shades of meaning hon.',
    synonyms: ['subtle', 'refined'],
    example: 'Her nuanced analysis avoided oversimplifying a complex issue.',
    memoryTip: 'NUANCE = shade of color → shades of meaning.',
    category: 'Academic & Formal'
  },
  {
    word: 'ambiguous',
    phonetic: 'am-BIG-yoo-us',
    pos: 'adj',
    meaningEN: 'Open to more than one interpretation; unclear.',
    meaningUR: 'Jo clear na ho, do ya zyada meanings ho sakti hon.',
    synonyms: ['unclear', 'vague'],
    example: 'The contract language was ambiguous, leading to disputes.',
    memoryTip: 'AMBI = both + IG (drive) → driven two ways, unclear.',
    category: 'Academic & Formal'
  },
  {
    word: 'substantiate',
    phonetic: 'sub-STAN-shee-ayt',
    pos: 'verb',
    meaningEN: 'To provide evidence to prove that something is true.',
    meaningUR: 'Koi claim proof de kar saabit karna.',
    synonyms: ['corroborate', 'verify'],
    example: 'You must substantiate your argument with credible sources.',
    memoryTip: 'SUBSTANCE → give substance (proof) to a claim.',
    category: 'Academic & Formal'
  },
  {
    word: 'entail',
    phonetic: 'en-TAYL',
    pos: 'verb',
    meaningEN: 'To involve something as a necessary part or consequence.',
    meaningUR: 'Kisi cheez ke saath kuch aur bhi zaroori hona.',
    synonyms: ['involve', 'require'],
    example: 'Leading a team entails responsibility for others\' work.',
    memoryTip: 'EN + TAIL → tied to the end → necessarily follows.',
    category: 'Academic & Formal'
  },
  {
    word: 'empirical',
    phonetic: 'em-PEER-i-kul',
    pos: 'adj',
    meaningEN: 'Based on observation or experiment rather than theory alone.',
    meaningUR: 'Jo experience ya experiment se aaye, sirf theory se nahi.',
    synonyms: ['observed', 'experimental'],
    example: 'The study relied on empirical data collected in the field.',
    memoryTip: 'EMPIRIC = experience → learned by trying, not guessing.',
    category: 'Academic & Formal'
  },
  {
    word: 'rhetoric',
    phonetic: 'RET-uh-rik',
    pos: 'noun',
    meaningEN: 'The art of persuasive speaking or writing.',
    meaningUR: 'Logon ko convince karne wali speech ya writing ka style.',
    synonyms: ['oratory', 'eloquence'],
    example: 'Political rhetoric often sounds convincing but lacks substance.',
    memoryTip: 'RHETOR (Greek teacher) → skill of persuasive speech.',
    category: 'Academic & Formal'
  },
  {
    word: 'meticulous',
    phonetic: 'muh-TIK-yuh-lus',
    pos: 'adj',
    meaningEN: 'Showing great attention to every small detail.',
    meaningUR: 'Bohat careful aur detail mein kaam karne wala.',
    synonyms: ['thorough', 'precise'],
    example: 'She kept meticulous records of every experiment.',
    memoryTip: 'METICULUS (Latin) = fearful → afraid to miss a detail.',
    category: 'Academic & Formal'
  },
  {
    word: 'ubiquitous',
    phonetic: 'yoo-BIK-wi-tus',
    pos: 'adj',
    meaningEN: 'Present or found everywhere.',
    meaningUR: 'Har jagah maujood, bohat common.',
    synonyms: ['omnipresent', 'widespread'],
    example: 'Smartphones have become ubiquitous in urban life.',
    memoryTip: 'UBI (everywhere) + QUITOUS → found everywhere.',
    category: 'Academic & Formal'
  },
  {
    word: 'feasible',
    phonetic: 'FEE-zuh-bul',
    pos: 'adj',
    meaningEN: 'Possible and practical to do or achieve.',
    meaningUR: 'Jo realistically ho sakay, practical ho.',
    synonyms: ['pragmatic', 'viable'],
    example: 'The committee asked whether the timeline was feasible.',
    memoryTip: 'FEAS (do) + IBLE → able to be done.',
    category: 'Academic & Formal'
  },
  {
    word: 'coherent',
    phonetic: 'koh-HEER-ent',
    pos: 'adj',
    meaningEN: 'Logical and consistent; easy to understand as a whole.',
    meaningUR: 'Jo samajh mein aaye aur logically juri ho.',
    synonyms: ['logical', 'consistent'],
    example: 'A coherent essay connects each paragraph to the main thesis.',
    memoryTip: 'CO + HERERE (stick) → ideas stick together logically.',
    category: 'Academic & Formal'
  },

  // ── Emotions & Psychology (15) ──
  {
    word: 'apprehensive',
    phonetic: 'ap-ri-HEN-siv',
    pos: 'adj',
    meaningEN: 'Anxious or fearful that something bad may happen.',
    meaningUR: 'Thora dar lag raha ho ke kuch bura ho sakta hai.',
    synonyms: ['wary', 'anxious'],
    example: 'She felt apprehensive before her first university presentation.',
    memoryTip: 'APPREHEND = seize → mind seized by worry.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'elated',
    phonetic: 'ee-LAY-ted',
    pos: 'adj',
    meaningEN: 'Extremely happy and excited.',
    meaningUR: 'Bohat khush aur excited, jese jeet ke baad.',
    synonyms: ['exuberant', 'thrilled'],
    example: 'He was elated when he received the scholarship offer.',
    memoryTip: 'E + LATE → lifted high in spirits.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'apathetic',
    phonetic: 'ap-uh-THET-ik',
    pos: 'adj',
    meaningEN: 'Showing little or no interest or concern.',
    meaningUR: 'Beparwah, jisko kisi cheez se farq na paray.',
    synonyms: ['indifferent', 'complacent'],
    example: 'Voters grew apathetic after years of broken promises.',
    memoryTip: 'A (without) + PATHOS (feeling) → without feeling.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'resilient',
    phonetic: 'ri-ZIL-yent',
    pos: 'adj',
    meaningEN: 'Able to recover quickly from difficulties.',
    meaningUR: 'Mushkil ke baad jaldi sambhal jane wala.',
    synonyms: ['tough', 'adaptable'],
    example: 'Resilient communities rebuild faster after natural disasters.',
    memoryTip: 'RE + SALIRE (jump) → bounce back.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'melancholy',
    phonetic: 'MEL-un-kol-ee',
    pos: 'noun',
    meaningEN: 'A deep, persistent feeling of sadness.',
    meaningUR: 'Gehra udaasi ka ehsaas jo der tak rehta ho.',
    synonyms: ['sorrow', 'subdued'],
    example: 'Rainy afternoons often stirred a quiet melancholy in her.',
    memoryTip: 'MELAN (black) + CHOLY (bile) → dark mood in old medicine.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'serene',
    phonetic: 'suh-REEN',
    pos: 'adj',
    meaningEN: 'Calm, peaceful, and untroubled.',
    meaningUR: 'Sukoon bhara, bilkul shaant.',
    synonyms: ['tranquil', 'subdued'],
    example: 'The lake looked serene at dawn before anyone arrived.',
    memoryTip: 'Sounds like "serenity" → peaceful calm.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'volatile',
    phonetic: 'VOL-uh-til',
    pos: 'adj',
    meaningEN: 'Likely to change suddenly, especially in mood or temper.',
    meaningUR: 'Jo jaldi badal jaye, mood ya halat unstable ho.',
    synonyms: ['unstable', 'erratic'],
    example: 'His volatile temper made colleagues hesitant to disagree.',
    memoryTip: 'VOLATILE = evaporates fast → moods evaporate and shift.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'empathetic',
    phonetic: 'em-puh-THET-ik',
    pos: 'adj',
    meaningEN: 'Able to understand and share another person\'s feelings.',
    meaningUR: 'Doosre ke dard ya feelings samajhne wala.',
    synonyms: ['compassionate', 'understanding'],
    example: 'An empathetic listener validates feelings before offering advice.',
    memoryTip: 'EM + PATHOS → feeling with someone else\'s pathos.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'cynical',
    phonetic: 'SIN-i-kul',
    pos: 'adj',
    meaningEN: 'Believing people are motivated mainly by self-interest.',
    meaningUR: 'Jo har cheez mein selfish motive dekhe, trust na kare.',
    synonyms: ['skeptical', 'distrustful'],
    example: 'Years of scandal left voters cynical about politicians.',
    memoryTip: 'From Cynic philosophers who distrusted luxury and motives.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'indignant',
    phonetic: 'in-DIG-nunt',
    pos: 'adj',
    meaningEN: 'Angry because of something unfair or insulting.',
    meaningUR: 'Gussa jo unfair treatment ki wajah se ho.',
    synonyms: ['outraged', 'resentful'],
    example: 'She was indignant when her contribution was ignored.',
    memoryTip: 'IN + DIGNUS (worthy) → not treated as worthy → angry.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'nostalgic',
    phonetic: 'nos-TAL-jik',
    pos: 'adj',
    meaningEN: 'Feeling sentimental longing for the past.',
    meaningUR: 'Purani yaadon ki taraf attract hona, miss karna.',
    synonyms: ['wistful', 'sentimental'],
    example: 'Old photographs made him nostalgic for his childhood neighborhood.',
    memoryTip: 'NOSTOS (return home) + ALGOS (pain) → homesick longing.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'exuberant',
    phonetic: 'ig-ZOO-bur-unt',
    pos: 'adj',
    meaningEN: 'Full of energy, excitement, and cheerfulness.',
    meaningUR: 'Bohat zinda dil, khushi aur energy se bhara.',
    synonyms: ['elated', 'lively'],
    example: 'The exuberant crowd cheered throughout the entire concert.',
    memoryTip: 'EX (out) + UBER (fruitful) → overflowing with joy.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'subdued',
    phonetic: 'sub-DOOD',
    pos: 'adj',
    meaningEN: 'Quiet and less intense; restrained in emotion.',
    meaningUR: 'Thora shaant, kam energetic ya kam emotional.',
    synonyms: ['serene', 'melancholy'],
    example: 'After the news, the room fell into a subdued silence.',
    memoryTip: 'SUB (under) + DUCE (lead) → brought under control.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'wary',
    phonetic: 'WAIR-ee',
    pos: 'adj',
    meaningEN: 'Cautious about possible dangers or problems.',
    meaningUR: 'Hoshiyar aur careful, kuch galat ho sakta hai soch kar.',
    synonyms: ['apprehensive', 'cautious'],
    example: 'Investors grew wary of unpredictable market swings.',
    memoryTip: 'WARE (aware) → stay aware of risk.',
    category: 'Emotions & Psychology'
  },
  {
    word: 'complacent',
    phonetic: 'kum-PLAY-sunt',
    pos: 'adj',
    meaningEN: 'Self-satisfied and unaware of potential dangers.',
    meaningUR: 'Khud ko itna satisfied samajhna ke improvement bhool jao.',
    synonyms: ['apathetic', 'smug'],
    example: 'Success made the team complacent, and performance slipped.',
    memoryTip: 'COM + PLACERE (please) → pleased with yourself, no urgency.',
    category: 'Emotions & Psychology'
  },

  // ── Science & Technology (15) ──
  {
    word: 'algorithm',
    phonetic: 'AL-guh-rith-um',
    pos: 'noun',
    meaningEN: 'A step-by-step set of rules for solving a problem.',
    meaningUR: 'Computer ya math mein step-by-step solution ka tareeqa.',
    synonyms: ['procedure', 'formula'],
    example: 'The search engine uses a complex algorithm to rank results.',
    memoryTip: 'Named after mathematician al-Khwarizmi.',
    category: 'Science & Technology'
  },
  {
    word: 'hypothesis',
    phonetic: 'hy-POTH-uh-sis',
    pos: 'noun',
    meaningEN: 'An idea proposed for testing before it is proven.',
    meaningUR: 'Science mein pehle wali guess jo experiment se check ho.',
    synonyms: ['theory', 'assumption'],
    example: 'The researcher formed a hypothesis before collecting data.',
    memoryTip: 'HYPO (under) + THESIS (placement) → underlying guess.',
    category: 'Science & Technology'
  },
  {
    word: 'catalyst',
    phonetic: 'KAT-uh-list',
    pos: 'noun',
    meaningEN: 'Something that speeds up a change without being consumed.',
    meaningUR: 'Jo reaction ya change ko tez kar de bina khud khatam hue.',
    synonyms: ['trigger', 'accelerator'],
    example: 'The grant acted as a catalyst for new research projects.',
    memoryTip: 'CATA (down) + LYSIS (loosening) → breaks barriers to react.',
    category: 'Science & Technology'
  },
  {
    word: 'quantum',
    phonetic: 'KWON-tum',
    pos: 'noun',
    meaningEN: 'The smallest discrete unit of a physical property.',
    meaningUR: 'Physics mein sab se choti fixed amount of energy ya matter.',
    synonyms: ['particle', 'unit'],
    example: 'Quantum mechanics describes behavior at subatomic scales.',
    memoryTip: 'QUANTUS (Latin) = how much → smallest amount.',
    category: 'Science & Technology'
  },
  {
    word: 'prototype',
    phonetic: 'PROH-tuh-type',
    pos: 'noun',
    meaningEN: 'An early model built to test a design.',
    meaningUR: 'Pehla sample model jo test karne ke liye banaya jaye.',
    synonyms: ['model', 'mock-up'],
    example: 'Engineers tested the prototype before mass production.',
    memoryTip: 'PROTO (first) + TYPE → first version of a type.',
    category: 'Science & Technology'
  },
  {
    word: 'firmware',
    phonetic: 'FIRM-wair',
    pos: 'noun',
    meaningEN: 'Permanent software programmed into hardware devices.',
    meaningUR: 'Hardware ke andar lagi hui software jo update ho sakti hai.',
    synonyms: ['software', 'embedded code'],
    example: 'Updating the firmware fixed the router\'s connectivity bug.',
    memoryTip: 'FIRM (fixed) + WARE → software firm in the device.',
    category: 'Science & Technology'
  },
  {
    word: 'bandwidth',
    phonetic: 'BAND-width',
    pos: 'noun',
    meaningEN: 'The capacity of a network to transmit data.',
    meaningUR: 'Internet ya network kitni data ek waqt mein bhej sakta hai.',
    synonyms: ['capacity', 'throughput'],
    example: 'Video calls require more bandwidth than simple email.',
    memoryTip: 'BAND (range) + WIDTH → how wide the data pipe is.',
    category: 'Science & Technology'
  },
  {
    word: 'entropy',
    phonetic: 'EN-truh-pee',
    pos: 'noun',
    meaningEN: 'A measure of disorder or randomness in a system.',
    meaningUR: 'System mein disorder ya randomness ka level.',
    synonyms: ['disorder', 'chaos'],
    example: 'Entropy increases when energy spreads without organization.',
    memoryTip: 'EN (in) + TROPE (turn) → tendency toward disorder.',
    category: 'Science & Technology'
  },
  {
    word: 'radiation',
    phonetic: 'ray-dee-AY-shun',
    pos: 'noun',
    meaningEN: 'Energy emitted as waves or particles from a source.',
    meaningUR: 'Source se nikalne wali energy jaise light, heat, ya rays.',
    synonyms: ['emission', 'rays'],
    example: 'Sunscreen helps block harmful ultraviolet radiation.',
    memoryTip: 'RADIATE = rays spreading outward from a center.',
    category: 'Science & Technology'
  },
  {
    word: 'synthesize',
    phonetic: 'SIN-thuh-size',
    pos: 'verb',
    meaningEN: 'To combine parts into a whole, especially in chemistry or research.',
    meaningUR: 'Alag cheezon ko mila kar naya compound ya idea banana.',
    synonyms: ['combine', 'integrate'],
    example: 'The lab learned to synthesize the compound more efficiently.',
    memoryTip: 'SYN (together) + THESIS (placement) → put together.',
    category: 'Science & Technology'
  },
  {
    word: 'deploy',
    phonetic: 'di-PLOY',
    pos: 'verb',
    meaningEN: 'To put something into active use or position.',
    meaningUR: 'Kisi system ya team ko use ya field mein bhejna.',
    synonyms: ['implement', 'launch'],
    example: 'The company will deploy the update overnight.',
    memoryTip: 'DE + PLOY (fold) → unfold troops → put into action.',
    category: 'Science & Technology'
  },
  {
    word: 'authenticate',
    phonetic: 'aw-THEN-ti-kayt',
    pos: 'verb',
    meaningEN: 'To prove that something or someone is genuine.',
    meaningUR: 'Verify karna ke user ya document asli hai.',
    synonyms: ['verify', 'validate'],
    example: 'Users must authenticate with a password and code.',
    memoryTip: 'AUTHENTIC = real → make sure it is real.',
    category: 'Science & Technology'
  },
  {
    word: 'encrypted',
    phonetic: 'en-KRIP-ted',
    pos: 'adj',
    meaningEN: 'Converted into a secure code to prevent unauthorized access.',
    meaningUR: 'Data ko code mein convert kiya ho taake koi na parh sake.',
    synonyms: ['encoded', 'secured'],
    example: 'All encrypted messages require a private key to read.',
    memoryTip: 'CRYPT (hidden) → hide data inside a cipher.',
    category: 'Science & Technology'
  },
  {
    word: 'dormant',
    phonetic: 'DOR-munt',
    pos: 'adj',
    meaningEN: 'Temporarily inactive but capable of becoming active.',
    meaningUR: 'Sota hua lekin phir se active ho sakne wala.',
    synonyms: ['inactive', 'latent'],
    example: 'The dormant volcano has not erupted in centuries.',
    memoryTip: 'DORMIRE (sleep) → sleeping but not dead.',
    category: 'Science & Technology'
  },
  {
    word: 'trajectory',
    phonetic: 'truh-JEK-tuh-ree',
    pos: 'noun',
    meaningEN: 'The path followed by an object moving through space.',
    meaningUR: 'Kisi object ka rasta jahan wo move kar raha ho.',
    synonyms: ['path', 'course'],
    example: 'Scientists calculated the rocket\'s trajectory before launch.',
    memoryTip: 'TRAJECT (throw across) + ORY → path of a throw.',
    category: 'Science & Technology'
  },

  // ── Society & Politics (15) ──
  {
    word: 'democracy',
    phonetic: 'di-MOK-ruh-see',
    pos: 'noun',
    meaningEN: 'A system of government by the whole population through voting.',
    meaningUR: 'Logon ki government jahan vote se leader chunte hain.',
    synonyms: ['republic', 'self-rule'],
    example: 'A healthy democracy depends on informed citizens.',
    memoryTip: 'DEMOS (people) + KRATOS (rule) → rule by the people.',
    category: 'Society & Politics'
  },
  {
    word: 'sovereignty',
    phonetic: 'SOV-rin-tee',
    pos: 'noun',
    meaningEN: 'Supreme authority of a state to govern itself.',
    meaningUR: 'Kisi mulk ka apni marzi se faisla karne ka haq.',
    synonyms: ['autonomy', 'independence'],
    example: 'The treaty respected each nation\'s sovereignty.',
    memoryTip: 'SOVEREIGN = supreme ruler → supreme self-rule.',
    category: 'Society & Politics'
  },
  {
    word: 'legislation',
    phonetic: 'lej-is-LAY-shun',
    pos: 'noun',
    meaningEN: 'Laws considered collectively or the process of making them.',
    meaningUR: 'Parliament ya assembly se banne wale qanoon.',
    synonyms: ['statute', 'lawmaking'],
    example: 'New legislation aimed to reduce carbon emissions.',
    memoryTip: 'LEGIS (law) + LATION → act of making law.',
    category: 'Society & Politics'
  },
  {
    word: 'referendum',
    phonetic: 'ref-uh-REN-dum',
    pos: 'noun',
    meaningEN: 'A direct vote by the public on a specific issue.',
    meaningUR: 'Puri awam se kisi ek maslay par direct vote lena.',
    synonyms: ['plebiscite', 'ballot'],
    example: 'Citizens approved the reform in a national referendum.',
    memoryTip: 'REFER (carry back) → carry the question back to the people.',
    category: 'Society & Politics'
  },
  {
    word: 'disparity',
    phonetic: 'dis-PAR-uh-tee',
    pos: 'noun',
    meaningEN: 'A great difference, especially in wealth or opportunity.',
    meaningUR: 'Do groups ke darmiyan bada farq, jaise ameer aur ghareeb.',
    synonyms: ['inequality', 'gap'],
    example: 'Income disparity widened between urban and rural areas.',
    memoryTip: 'DIS (apart) + PAR (equal) → not equal → gap.',
    category: 'Society & Politics'
  },
  {
    word: 'propaganda',
    phonetic: 'prop-uh-GAN-duh',
    pos: 'noun',
    meaningEN: 'Biased information spread to promote a political cause.',
    meaningUR: 'Kisi party ke favour mein biased news ya messaging.',
    synonyms: ['rhetoric', 'spin'],
    example: 'State propaganda portrayed critics as enemies of progress.',
    memoryTip: 'PROPAGARE (spread) → spread a one-sided message.',
    category: 'Society & Politics'
  },
  {
    word: 'consensus',
    phonetic: 'kun-SEN-sus',
    pos: 'noun',
    meaningEN: 'General agreement among a group of people.',
    meaningUR: 'Sab ka mil kar ek hi raay par aa jana.',
    synonyms: ['agreement', 'unity'],
    example: 'The council reached consensus after hours of debate.',
    memoryTip: 'CON (together) + SENSUS (feeling) → feel together → agree.',
    category: 'Society & Politics'
  },
  {
    word: 'jurisdiction',
    phonetic: 'joor-is-DIK-shun',
    pos: 'noun',
    meaningEN: 'The official power to make legal decisions in an area.',
    meaningUR: 'Kisi court ya authority ka legal power ka area.',
    synonyms: ['authority', 'domain'],
    example: 'The case fell outside the court\'s jurisdiction.',
    memoryTip: 'JURIS (law) + DICTION (saying) → where law speaks.',
    category: 'Society & Politics'
  },
  {
    word: 'insurgency',
    phonetic: 'in-SUR-jun-see',
    pos: 'noun',
    meaningEN: 'An active revolt against an established government.',
    meaningUR: 'Government ke khilaf armed ya organized rebellion.',
    synonyms: ['rebellion', 'uprising'],
    example: 'The insurgency disrupted trade along the border region.',
    memoryTip: 'IN (against) + SURGE (rise up) → rise against power.',
    category: 'Society & Politics'
  },
  {
    word: 'bureaucracy',
    phonetic: 'byoo-ROK-ruh-see',
    pos: 'noun',
    meaningEN: 'A system of government with many complicated rules and officials.',
    meaningUR: 'Official departments ka complex system jahan paperwork zyada ho.',
    synonyms: ['administration', 'red tape'],
    example: 'Small businesses struggled with layers of bureaucracy.',
    memoryTip: 'BUREAU (office) + CRACY (rule) → rule by offices and forms.',
    category: 'Society & Politics'
  },
  {
    word: 'secular',
    phonetic: 'SEK-yuh-lur',
    pos: 'adj',
    meaningEN: 'Not connected with religious or spiritual matters.',
    meaningUR: 'Din se alag, neutral government ya society.',
    synonyms: ['nonreligious', 'civic'],
    example: 'The constitution guarantees a secular education system.',
    memoryTip: 'From Latin saeculum (age/world) → of this world, not church.',
    category: 'Society & Politics'
  },
  {
    word: 'affiliation',
    phonetic: 'uh-fil-ee-AY-shun',
    pos: 'noun',
    meaningEN: 'Official connection with an organization or group.',
    meaningUR: 'Kisi party, group, ya organization se official link.',
    synonyms: ['association', 'membership'],
    example: 'The journalist disclosed her affiliation with the advocacy group.',
    memoryTip: 'AFFILIATE = adopt as a child → adopt as member.',
    category: 'Society & Politics'
  },
  {
    word: 'amendment',
    phonetic: 'uh-MEND-munt',
    pos: 'noun',
    meaningEN: 'A formal change or addition to a law or document.',
    meaningUR: 'Qanoon ya constitution mein official change.',
    synonyms: ['revision', 'modification'],
    example: 'The amendment strengthened protections for free speech.',
    memoryTip: 'AMEND = fix → a fix written into the law.',
    category: 'Society & Politics'
  },
  {
    word: 'oppression',
    phonetic: 'uh-PRESH-un',
    pos: 'noun',
    meaningEN: 'Prolonged cruel or unjust treatment of a group.',
    meaningUR: 'Kisi group par zulm ya unfair control.',
    synonyms: ['tyranny', 'disparity'],
    example: 'Historians documented decades of oppression under the regime.',
    memoryTip: 'OPPRESS = press down → weigh people down unjustly.',
    category: 'Society & Politics'
  },
  {
    word: 'diplomacy',
    phonetic: 'di-PLOH-muh-see',
    pos: 'noun',
    meaningEN: 'The skill of managing international relations peacefully.',
    meaningUR: 'Countries ke beech peaceful negotiation ka fun.',
    synonyms: ['negotiation', 'tact'],
    example: 'Diplomacy prevented the trade dispute from escalating.',
    memoryTip: 'DIPLOMA (folded document) → official papers between states.',
    category: 'Society & Politics'
  },

  // ── Environment & Nature (15) ──
  {
    word: 'biodiversity',
    phonetic: 'by-oh-dy-VUR-suh-tee',
    pos: 'noun',
    meaningEN: 'The variety of plant and animal life in a habitat.',
    meaningUR: 'Ek area mein plants aur animals ki variety.',
    synonyms: ['variety', 'ecosystem'],
    example: 'Rainforests support extraordinary biodiversity.',
    memoryTip: 'BIO (life) + DIVERSITY → diverse forms of life.',
    category: 'Environment & Nature'
  },
  {
    word: 'ecosystem',
    phonetic: 'EE-koh-sis-tum',
    pos: 'noun',
    meaningEN: 'A community of living things interacting with their environment.',
    meaningUR: 'Plants, animals, aur environment ka interconnected system.',
    synonyms: ['habitat', 'biodiversity'],
    example: 'Pollution can destabilize an entire ecosystem.',
    memoryTip: 'ECO (house) + SYSTEM → house of living parts working together.',
    category: 'Environment & Nature'
  },
  {
    word: 'sustainable',
    phonetic: 'sus-TAY-nuh-bul',
    pos: 'adj',
    meaningEN: 'Able to continue without depleting natural resources.',
    meaningUR: 'Jo environment ko nuqsan na pohanchaye aur lamba chal sake.',
    synonyms: ['renewable', 'conservation'],
    example: 'Farmers adopted sustainable methods to protect soil health.',
    memoryTip: 'SUSTAIN = hold up → hold up for the long term.',
    category: 'Environment & Nature'
  },
  {
    word: 'deforestation',
    phonetic: 'dee-for-uh-STAY-shun',
    pos: 'noun',
    meaningEN: 'The clearing of forests on a large scale.',
    meaningUR: 'Janglat ka kaat kar khatam karna.',
    synonyms: ['clearing', 'logging'],
    example: 'Deforestation threatens species that depend on tree cover.',
    memoryTip: 'DE (remove) + FOREST → remove the forest.',
    category: 'Environment & Nature'
  },
  {
    word: 'erosion',
    phonetic: 'i-ROH-zhun',
    pos: 'noun',
    meaningEN: 'The gradual wearing away of soil or rock by wind or water.',
    meaningUR: 'Matti ya patthar ka dheere dheere water ya hawa se ghisna.',
    synonyms: ['wear', 'degradation'],
    example: 'Coastal erosion forced several villages to relocate.',
    memoryTip: 'ERODE = eat away → gnawed by elements.',
    category: 'Environment & Nature'
  },
  {
    word: 'renewable',
    phonetic: 'ri-NOO-vuh-bul',
    pos: 'adj',
    meaningEN: 'Able to be replenished naturally and not permanently used up.',
    meaningUR: 'Jo dubara ban jaye, jaise solar ya wind energy.',
    synonyms: ['sustainable', 'green'],
    example: 'The city invested in renewable energy for public buildings.',
    memoryTip: 'RE + NEW → made new again by nature.',
    category: 'Environment & Nature'
  },
  {
    word: 'drought',
    phonetic: 'drowt',
    pos: 'noun',
    meaningEN: 'A long period of abnormally low rainfall.',
    meaningUR: 'Lambi barish na honay ki wajah se sukha.',
    synonyms: ['dry spell', 'aridity'],
    example: 'The drought destroyed crops across the region.',
    memoryTip: 'Sounds like "dry out" → land dries out.',
    category: 'Environment & Nature'
  },
  {
    word: 'habitat',
    phonetic: 'HAB-uh-tat',
    pos: 'noun',
    meaningEN: 'The natural home of an animal or plant.',
    meaningUR: 'Jis jagah koi janwar ya plant naturally rehta ho.',
    synonyms: ['ecosystem', 'environment'],
    example: 'Wetlands provide critical habitat for migratory birds.',
    memoryTip: 'HABIT + AT → where a species has its habit of living.',
    category: 'Environment & Nature'
  },
  {
    word: 'contaminate',
    phonetic: 'kun-TAM-uh-nayt',
    pos: 'verb',
    meaningEN: 'To make something impure or poisonous.',
    meaningUR: 'Pani, khana, ya soil ko ganda ya toxic banana.',
    synonyms: ['pollute', 'taint'],
    example: 'Industrial waste can contaminate drinking water supplies.',
    memoryTip: 'CONTACT + TAINT → touch and taint.',
    category: 'Environment & Nature'
  },
  {
    word: 'conservation',
    phonetic: 'kon-sur-VAY-shun',
    pos: 'noun',
    meaningEN: 'The protection of natural resources from waste or harm.',
    meaningUR: 'Nature ko bachane aur resources ko waste se bachane ka kaam.',
    synonyms: ['preservation', 'sustainable'],
    example: 'Conservation programs helped restore the endangered species.',
    memoryTip: 'CONSERVE = keep safe → keeping nature safe.',
    category: 'Environment & Nature'
  },
  {
    word: 'emission',
    phonetic: 'i-MISH-un',
    pos: 'noun',
    meaningEN: 'Gas or radiation released into the atmosphere.',
    meaningUR: 'Factories ya vehicles se nikalne wala gas ya smoke.',
    synonyms: ['radiation', 'discharge'],
    example: 'Governments set targets to cut carbon emissions.',
    memoryTip: 'EMIT = send out → what is sent out.',
    category: 'Environment & Nature'
  },
  {
    word: 'ozone',
    phonetic: 'OH-zone',
    pos: 'noun',
    meaningEN: 'A form of oxygen that blocks harmful ultraviolet rays.',
    meaningUR: 'Atmosphere ki layer jo harmful UV rays rokti hai.',
    synonyms: ['atmosphere', 'layer'],
    example: 'Scientists monitor holes in the ozone layer each year.',
    memoryTip: 'OZEIN (Greek smell) → sharp smell near electrical sparks.',
    category: 'Environment & Nature'
  },
  {
    word: 'watershed',
    phonetic: 'WAW-ter-shed',
    pos: 'noun',
    meaningEN: 'An area of land where all water drains to one river or lake.',
    meaningUR: 'Wo area jahan ka sara pani ek river ya lake mein jata ho.',
    synonyms: ['basin', 'drainage'],
    example: 'Fertilizer runoff polluted the entire watershed.',
    memoryTip: 'WATER + SHED (divide) → land that sheds water one way.',
    category: 'Environment & Nature'
  },
  {
    word: 'indigenous',
    phonetic: 'in-DIJ-uh-nus',
    pos: 'adj',
    meaningEN: 'Native to a particular region rather than introduced from elsewhere.',
    meaningUR: 'Jo kisi jagah ka apna ho, bahar se na aaya ho.',
    synonyms: ['native', 'local'],
    example: 'Indigenous plants adapted to the dry climate over centuries.',
    memoryTip: 'INDU (within) + GEN (born) → born in that place.',
    category: 'Environment & Nature'
  },
  {
    word: 'preserve',
    phonetic: 'pri-ZURV',
    pos: 'verb',
    meaningEN: 'To keep something in its original or safe condition.',
    meaningUR: 'Kisi cheez ko bachana ya uski halat maintain karna.',
    synonyms: ['conservation', 'protect'],
    example: 'National parks preserve wilderness for future generations.',
    memoryTip: 'PRE (before) + SERVE → keep as it was before.',
    category: 'Environment & Nature'
  },

  // ── Business & Economics (15) ──
  {
    word: 'revenue',
    phonetic: 'REV-uh-noo',
    pos: 'noun',
    meaningEN: 'Income generated from business operations or sales.',
    meaningUR: 'Business se aane wala total paisa ya income.',
    synonyms: ['income', 'earnings'],
    example: 'Online sales boosted the company\'s quarterly revenue.',
    memoryTip: 'RE + VENIRE (come) → money that comes in.',
    category: 'Business & Economics'
  },
  {
    word: 'inflation',
    phonetic: 'in-FLAY-shun',
    pos: 'noun',
    meaningEN: 'A general rise in prices reducing the value of money.',
    meaningUR: 'Cheezon ki qeematon ka barhna, paisay ki value kam hona.',
    synonyms: ['price rise', 'stagnation'],
    example: 'Inflation made everyday groceries more expensive.',
    memoryTip: 'INFLATE like a balloon → prices swell up.',
    category: 'Business & Economics'
  },
  {
    word: 'austerity',
    phonetic: 'aw-STAIR-uh-tee',
    pos: 'noun',
    meaningEN: 'Strict economy measures to reduce government spending.',
    meaningUR: 'Government ka kharch kam karne ke liye strict policies.',
    synonyms: ['cutbacks', 'frugality'],
    example: 'Austerity programs reduced public services in several countries.',
    memoryTip: 'AUSTERE = harshly simple → harsh spending cuts.',
    category: 'Business & Economics'
  },
  {
    word: 'monopoly',
    phonetic: 'muh-NOP-uh-lee',
    pos: 'noun',
    meaningEN: 'Exclusive control of a product or market by one supplier.',
    meaningUR: 'Ek hi company ka market par poora control.',
    synonyms: ['dominance', 'control'],
    example: 'Regulators broke up the monopoly to encourage competition.',
    memoryTip: 'MONO (one) + POLY (sell) → one seller rules.',
    category: 'Business & Economics'
  },
  {
    word: 'dividend',
    phonetic: 'DIV-uh-dend',
    pos: 'noun',
    meaningEN: 'A share of profits paid to company shareholders.',
    meaningUR: 'Company ka profit shareholders mein baantna.',
    synonyms: ['payout', 'yield'],
    example: 'Investors welcomed the higher dividend this quarter.',
    memoryTip: 'DIVIDE + END → profits divided at year\'s end.',
    category: 'Business & Economics'
  },
  {
    word: 'fiscal',
    phonetic: 'FIS-kul',
    pos: 'adj',
    meaningEN: 'Relating to government revenue, taxes, and public spending.',
    meaningUR: 'Government ke budget, tax, aur kharch se related.',
    synonyms: ['financial', 'budgetary'],
    example: 'The fiscal year ends in June for this ministry.',
    memoryTip: 'FISCUS (Latin basket) → public money basket.',
    category: 'Business & Economics'
  },
  {
    word: 'venture',
    phonetic: 'VEN-chur',
    pos: 'noun',
    meaningEN: 'A new business project involving risk.',
    meaningUR: 'Naya business idea jisme risk ho lekin profit bhi.',
    synonyms: ['enterprise', 'startup'],
    example: 'They launched a joint venture to enter overseas markets.',
    memoryTip: 'VENTURE = dare to go → risky new journey.',
    category: 'Business & Economics'
  },
  {
    word: 'leverage',
    phonetic: 'LEV-ur-ij',
    pos: 'verb',
    meaningEN: 'To use something to maximum advantage, often with borrowed capital.',
    meaningUR: 'Kisi resource ko poori tarah use karna, kabhi loan se bhi.',
    synonyms: ['utilize', 'exploit'],
    example: 'The firm leveraged its brand to expand into new sectors.',
    memoryTip: 'LEVER lifts heavy loads → lift results with less effort.',
    category: 'Business & Economics'
  },
  {
    word: 'tariff',
    phonetic: 'TAIR-if',
    pos: 'noun',
    meaningEN: 'A tax on imported or exported goods.',
    meaningUR: 'Import ya export par government ka tax.',
    synonyms: ['duty', 'levy'],
    example: 'Higher tariffs raised the cost of imported electronics.',
    memoryTip: 'Old ARABIC ta\'rif = notification → listed tax on goods.',
    category: 'Business & Economics'
  },
  {
    word: 'surplus',
    phonetic: 'SUR-plus',
    pos: 'noun',
    meaningEN: 'An amount left over when needs are met.',
    meaningUR: 'Zarurat se zyada bacha hua stock ya paisa.',
    synonyms: ['excess', 'remainder'],
    example: 'The budget surplus funded new infrastructure projects.',
    memoryTip: 'SUR (over) + PLUS (more) → more than needed.',
    category: 'Business & Economics'
  },
  {
    word: 'bankruptcy',
    phonetic: 'BANGK-rupt-see',
    pos: 'noun',
    meaningEN: 'Legal status when a person or company cannot pay debts.',
    meaningUR: 'Jab koi apne debts ada na kar sake aur court case ho.',
    synonyms: ['insolvency', 'failure'],
    example: 'Rising costs pushed the retailer into bankruptcy.',
    memoryTip: 'BANK + RUPT (break) → broken bank account.',
    category: 'Business & Economics'
  },
  {
    word: 'equity',
    phonetic: 'EK-wuh-tee',
    pos: 'noun',
    meaningEN: 'Ownership interest in a company, or fairness in treatment.',
    meaningUR: 'Company mein share ya fair treatment ka concept.',
    synonyms: ['ownership', 'fairness'],
    example: 'Employees received equity as part of their compensation package.',
    memoryTip: 'EQUAL → fair share → ownership share.',
    category: 'Business & Economics'
  },
  {
    word: 'procurement',
    phonetic: 'proh-KYOOR-munt',
    pos: 'noun',
    meaningEN: 'The process of obtaining goods or services for an organization.',
    meaningUR: 'Company ke liye saman ya services khareedne ka process.',
    synonyms: ['obtain', 'purchasing'],
    example: 'Central procurement reduced costs across all departments.',
    memoryTip: 'PROCURE = get for → act of getting supplies.',
    category: 'Business & Economics'
  },
  {
    word: 'merger',
    phonetic: 'MUR-jur',
    pos: 'noun',
    meaningEN: 'The combination of two companies into one.',
    meaningUR: 'Do companies ka mil kar ek banana.',
    synonyms: ['acquisition', 'union'],
    example: 'The merger created the largest airline in the region.',
    memoryTip: 'MERGE = blend together → two firms blend.',
    category: 'Business & Economics'
  },
  {
    word: 'stagnation',
    phonetic: 'stag-NAY-shun',
    pos: 'noun',
    meaningEN: 'A period of little or no economic growth.',
    meaningUR: 'Economy ka ruk jana, growth na hona.',
    synonyms: ['slump', 'inflation'],
    example: 'Policy makers debated how to escape years of stagnation.',
    memoryTip: 'STAGNANT water → economy stops flowing.',
    category: 'Business & Economics'
  },

  // ── Health & Medicine (15) ──
  {
    word: 'diagnosis',
    phonetic: 'dy-ug-NOH-sis',
    pos: 'noun',
    meaningEN: 'Identification of a disease from its signs and symptoms.',
    meaningUR: 'Doctor ka bimari identify karna symptoms se.',
    synonyms: ['evaluate', 'assessment'],
    example: 'An early diagnosis improved the patient\'s chances of recovery.',
    memoryTip: 'DIA (through) + GNOSIS (knowing) → know through signs.',
    category: 'Health & Medicine'
  },
  {
    word: 'chronic',
    phonetic: 'KRON-ik',
    pos: 'adj',
    meaningEN: 'Persisting for a long time or constantly recurring.',
    meaningUR: 'Lambi bimari jo jaldi theek na ho.',
    synonyms: ['persistent', 'long-term'],
    example: 'Chronic pain affected her ability to sleep at night.',
    memoryTip: 'CHRONOS (time) → lasts across time.',
    category: 'Health & Medicine'
  },
  {
    word: 'antibody',
    phonetic: 'AN-ti-bod-ee',
    pos: 'noun',
    meaningEN: 'A protein produced by the body to fight specific infections.',
    meaningUR: 'Body ka protein jo infection se ladta hai.',
    synonyms: ['immunity', 'defender'],
    example: 'Vaccines train the immune system to produce antibodies.',
    memoryTip: 'ANTI (against) + BODY → body fights back.',
    category: 'Health & Medicine'
  },
  {
    word: 'vaccine',
    phonetic: 'vak-SEEN',
    pos: 'noun',
    meaningEN: 'A substance that stimulates immunity to a disease.',
    meaningUR: 'Injection jo body ko bimari se defend karna sikhati hai.',
    synonyms: ['immunization', 'shot'],
    example: 'The vaccine rollout reached rural clinics within months.',
    memoryTip: 'From vacca (cow) → cowpox led to modern vaccines.',
    category: 'Health & Medicine'
  },
  {
    word: 'symptom',
    phonetic: 'SIMP-tum',
    pos: 'noun',
    meaningEN: 'A physical or mental sign indicating a condition or disease.',
    meaningUR: 'Bimari ki nishani jo patient feel ya dikhe.',
    synonyms: ['sign', 'indicator'],
    example: 'Fever is a common symptom of many viral infections.',
    memoryTip: 'SYM (together) + PTOM (fall) → signs that fall together.',
    category: 'Health & Medicine'
  },
  {
    word: 'prognosis',
    phonetic: 'prog-NOH-sis',
    pos: 'noun',
    meaningEN: 'A forecast of the likely course of a disease.',
    meaningUR: 'Doctor ka andaza ke bimari aage kaisi chale gi.',
    synonyms: ['outlook', 'forecast'],
    example: 'With treatment, the prognosis for full recovery was good.',
    memoryTip: 'PRO (before) + GNOSIS (knowing) → know beforehand.',
    category: 'Health & Medicine'
  },
  {
    word: 'placebo',
    phonetic: 'pluh-SEE-boh',
    pos: 'noun',
    meaningEN: 'An inactive treatment given to compare with a real drug.',
    meaningUR: 'Fake treatment jo sirf test ke liye di jaye, asli drug nahi.',
    synonyms: ['sham', 'dummy'],
    example: 'Half the participants received a placebo instead of the drug.',
    memoryTip: 'Latin "I shall please" → pleases mind, not chemistry.',
    category: 'Health & Medicine'
  },
  {
    word: 'sterile',
    phonetic: 'STAIR-il',
    pos: 'adj',
    meaningEN: 'Free from bacteria and other living microorganisms.',
    meaningUR: 'Bilkul saaf, germs se free, surgery ke liye.',
    synonyms: ['clean', 'aseptic'],
    example: 'Nurses opened sterile equipment before the operation.',
    memoryTip: 'STERILIS (barren) → nothing alive grows on it.',
    category: 'Health & Medicine'
  },
  {
    word: 'inflammation',
    phonetic: 'in-fluh-MAY-shun',
    pos: 'noun',
    meaningEN: 'Redness, swelling, and pain as the body responds to injury.',
    meaningUR: 'Zakham ya infection par sujan, laal pan, aur dard.',
    synonyms: ['swelling', 'irritation'],
    example: 'Ice reduced inflammation in the sprained ankle.',
    memoryTip: 'FLAME → area looks hot and red like fire.',
    category: 'Health & Medicine'
  },
  {
    word: 'epidemic',
    phonetic: 'ep-uh-DEM-ik',
    pos: 'noun',
    meaningEN: 'A widespread occurrence of a disease in a community.',
    meaningUR: 'Ek area mein bimari ka tezi se phailna.',
    synonyms: ['outbreak', 'ubiquitous'],
    example: 'Public health teams contained the flu epidemic quickly.',
    memoryTip: 'EPi (upon) + DEMOS (people) → upon the people.',
    category: 'Health & Medicine'
  },
  {
    word: 'regimen',
    phonetic: 'REJ-uh-men',
    pos: 'noun',
    meaningEN: 'A prescribed course of diet, exercise, or medical treatment.',
    meaningUR: 'Doctor ka bataya hua routine — dawai, diet, ya exercise.',
    synonyms: ['routine', 'protocol'],
    example: 'She followed a strict regimen after knee surgery.',
    memoryTip: 'REGIME = ruled plan → ruled health plan.',
    category: 'Health & Medicine'
  },
  {
    word: 'metabolic',
    phonetic: 'met-uh-BOL-ik',
    pos: 'adj',
    meaningEN: 'Relating to chemical processes that maintain life in the body.',
    meaningUR: 'Body ke andar chemical processes se related.',
    synonyms: ['physiological', 'energy'],
    example: 'Exercise boosts metabolic rate and burns calories.',
    memoryTip: 'META (change) + BOL (throw) → chemical changes in cells.',
    category: 'Health & Medicine'
  },
  {
    word: 'rehabilitate',
    phonetic: 'ree-huh-BIL-uh-tayt',
    pos: 'verb',
    meaningEN: 'To restore someone to health or normal life through training.',
    meaningUR: 'Bimari ya injury ke baad normal life par wapas lana.',
    synonyms: ['recover', 'restore'],
    example: 'Therapy helped rehabilitate patients after the stroke.',
    memoryTip: 'RE + HABILIS (able) → make able again.',
    category: 'Health & Medicine'
  },
  {
    word: 'immunity',
    phonetic: 'ih-MYOO-nuh-tee',
    pos: 'noun',
    meaningEN: 'Resistance to a particular infection or disease.',
    meaningUR: 'Body ki ability ke koi bimari na lage ya kam lage.',
    synonyms: ['antibody', 'resistance'],
    example: 'Childhood exposure can build immunity to common viruses.',
    memoryTip: 'IMMUNE = exempt → exempt from illness.',
    category: 'Health & Medicine'
  },
  {
    word: 'dosage',
    phonetic: 'DOH-sij',
    pos: 'noun',
    meaningEN: 'The amount of medicine to be taken at one time.',
    meaningUR: 'Ek waqt mein kitni dawai leni hai.',
    synonyms: ['dose', 'amount'],
    example: 'The pharmacist explained the correct dosage on the label.',
    memoryTip: 'DOSE + AGE → how much per taking.',
    category: 'Health & Medicine'
  },

  // ── Everyday Formal (15) ──
  {
    word: 'accommodate',
    phonetic: 'uh-KOM-uh-dayt',
    pos: 'verb',
    meaningEN: 'To provide space or adjust to meet someone\'s needs.',
    meaningUR: 'Kisi ki zarurat ke mutabiq jagah dena ya adjust karna.',
    synonyms: ['facilitate', 'adjust'],
    example: 'The hotel can accommodate groups of up to fifty guests.',
    memoryTip: 'AC + COMMODATE (fit) → make fit for someone.',
    category: 'Everyday Formal'
  },
  {
    word: 'postpone',
    phonetic: 'post-PONE',
    pos: 'verb',
    meaningEN: 'To arrange for something to happen at a later time.',
    meaningUR: 'Kisi meeting ya kaam ko baad ke liye rakhna.',
    synonyms: ['delay', 'defer'],
    example: 'They decided to postpone the meeting until next Monday.',
    memoryTip: 'POST (after) + PONE (put) → put after later.',
    category: 'Everyday Formal'
  },
  {
    word: 'facilitate',
    phonetic: 'fuh-SIL-uh-tayt',
    pos: 'verb',
    meaningEN: 'To make an action or process easier.',
    meaningUR: 'Kisi kaam ko asaan banana ya help karna.',
    synonyms: ['accommodate', 'enable'],
    example: 'The app facilitates communication between team members.',
    memoryTip: 'FACILE (easy) → make easy.',
    category: 'Everyday Formal'
  },
  {
    word: 'negotiate',
    phonetic: 'ni-GOH-shee-ayt',
    pos: 'verb',
    meaningEN: 'To discuss terms in order to reach an agreement.',
    meaningUR: 'Baat cheet kar deal ya agreement banana.',
    synonyms: ['diplomacy', 'bargain'],
    example: 'Both sides agreed to negotiate a fair settlement.',
    memoryTip: 'NEG (not) + OTium (leisure) → not idle → talk terms.',
    category: 'Everyday Formal'
  },
  {
    word: 'relevant',
    phonetic: 'REL-uh-vunt',
    pos: 'adj',
    meaningEN: 'Closely connected to the matter being discussed.',
    meaningUR: 'Jo topic se related ho, kaam ki baat ho.',
    synonyms: ['pertinent', 'applicable'],
    example: 'Please include only relevant details in your application.',
    memoryTip: 'RE + LEVARE (lift) → lift up to the topic at hand.',
    category: 'Everyday Formal'
  },
  {
    word: 'prior',
    phonetic: 'PRY-or',
    pos: 'adj',
    meaningEN: 'Existing or happening before something else.',
    meaningUR: 'Pehle wala, jo baad wali cheez se age ho.',
    synonyms: ['earlier', 'previous'],
    example: 'Prior experience in customer service is preferred.',
    memoryTip: 'PRI = before → comes first in line.',
    category: 'Everyday Formal'
  },
  {
    word: 'sufficient',
    phonetic: 'suh-FISH-unt',
    pos: 'adj',
    meaningEN: 'Enough to meet a need or purpose.',
    meaningUR: 'Itna kaafi ho jitni zarurat ho.',
    synonyms: ['adequate', 'feasible'],
    example: 'One page is sufficient for this short writing task.',
    memoryTip: 'SUF (under) + FICERE (make) → made underneath enough.',
    category: 'Everyday Formal'
  },
  {
    word: 'decline',
    phonetic: 'dih-KLYNE',
    pos: 'verb',
    meaningEN: 'To politely refuse an offer or invitation.',
    meaningUR: 'Nazuk tareeqe se offer ya invitation mana karna.',
    synonyms: ['refuse', 'reject'],
    example: 'She had to decline the invitation due to a prior commitment.',
    memoryTip: 'DE + CLINE (bend) → bend away → say no politely.',
    category: 'Everyday Formal'
  },
  {
    word: 'obtain',
    phonetic: 'ub-TAYN',
    pos: 'verb',
    meaningEN: 'To get or acquire something, especially through effort.',
    meaningUR: 'Koshish kar ke kuch hasil karna ya lena.',
    synonyms: ['procurement', 'acquire'],
    example: 'Students must obtain permission before leaving campus.',
    memoryTip: 'OB (toward) + TAIN (hold) → hold toward you → get.',
    category: 'Everyday Formal'
  },
  {
    word: 'comprise',
    phonetic: 'kum-PRYZ',
    pos: 'verb',
    meaningEN: 'To consist of or be made up of particular parts.',
    meaningUR: 'Kisi cheez ke parts ya members hona.',
    synonyms: ['include', 'contain'],
    example: 'The committee comprises representatives from five departments.',
    memoryTip: 'COMP (together) + PRISE (take) → taken together as a whole.',
    category: 'Everyday Formal'
  },
  {
    word: 'implement',
    phonetic: 'IM-pluh-ment',
    pos: 'verb',
    meaningEN: 'To put a plan or decision into effect.',
    meaningUR: 'Plan ya policy ko practically start karna.',
    synonyms: ['deploy', 'execute'],
    example: 'The school will implement the new policy next semester.',
    memoryTip: 'IMPL (fill) + MENT → fill with action.',
    category: 'Everyday Formal'
  },
  {
    word: 'preliminary',
    phonetic: 'pri-LIM-uh-ner-ee',
    pos: 'adj',
    meaningEN: 'Coming before the main part; introductory.',
    meaningUR: 'Asal kaam se pehle wala, intro ya first step.',
    synonyms: ['initial', 'prior'],
    example: 'Preliminary results suggest the treatment is effective.',
    memoryTip: 'PRE (before) + LIMEN (threshold) → before the threshold.',
    category: 'Everyday Formal'
  },
  {
    word: 'courteous',
    phonetic: 'KUR-tee-us',
    pos: 'adj',
    meaningEN: 'Polite and respectful in manner.',
    meaningUR: 'Meharban aur respectful behaviour wala.',
    synonyms: ['polite', 'gracious'],
    example: 'A courteous reply can ease tension in difficult emails.',
    memoryTip: 'COURT → manners of the royal court → polite.',
    category: 'Everyday Formal'
  },
  {
    word: 'procedure',
    phonetic: 'pruh-SEE-jur',
    pos: 'noun',
    meaningEN: 'An established or official way of doing something.',
    meaningUR: 'Kisi kaam ka fixed tareeqa ya official steps.',
    synonyms: ['algorithm', 'protocol'],
    example: 'Follow the safety procedure before entering the lab.',
    memoryTip: 'PROCEED + URE → the way you proceed step by step.',
    category: 'Everyday Formal'
  },
  {
    word: 'evaluate',
    phonetic: 'ih-VAL-yoo-ayt',
    pos: 'verb',
    meaningEN: 'To judge or assess the value or quality of something.',
    meaningUR: 'Kisi cheez ki value ya quality check karna.',
    synonyms: ['diagnosis', 'assess'],
    example: 'Teachers evaluate essays using a clear rubric.',
    memoryTip: 'E + VALUE → find the value of something.',
    category: 'Everyday Formal'
  }
];
